[package]
name = "rabbit-audit-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite = "2.6.0"
lapin = "=2.5.1"
tokio = { version = "1", features = ["full"] }
tokio-executor-trait = "2.1.3"
tokio-reactor-trait = "2.0.0"
